import { AlphabetLetter } from '../types';
import { letterColors } from './theme';

export const ROMANIAN_ALPHABET: AlphabetLetter[] = [
  { letter: 'A', example: 'Arici', emoji: '🦔', phonetic: 'A', color: letterColors[0] },
  { letter: 'Ă', example: 'Ăsta', emoji: '👆', phonetic: 'Ă', color: letterColors[1] },
  { letter: 'Â', example: 'Âncă', emoji: '✨', phonetic: 'Â', color: letterColors[2] },
  { letter: 'B', example: 'Balon', emoji: '🎈', phonetic: 'Be', color: letterColors[3] },
  { letter: 'C', example: 'Casă', emoji: '🏠', phonetic: 'Ce', color: letterColors[4] },
  { letter: 'D', example: 'Dinozaur', emoji: '🦕', phonetic: 'De', color: letterColors[5] },
  { letter: 'E', example: 'Elefant', emoji: '🐘', phonetic: 'E', color: letterColors[6] },
  { letter: 'F', example: 'Floare', emoji: '🌸', phonetic: 'Fe', color: letterColors[7] },
  { letter: 'G', example: 'Găină', emoji: '🐔', phonetic: 'Ghe', color: letterColors[8] },
  { letter: 'H', example: 'Hartă', emoji: '🗺️', phonetic: 'Ha', color: letterColors[9] },
  { letter: 'I', example: 'Iepure', emoji: '🐰', phonetic: 'I', color: letterColors[10] },
  { letter: 'Î', example: 'Înger', emoji: '😇', phonetic: 'Î', color: letterColors[11] },
  { letter: 'J', example: 'Jucărie', emoji: '🪀', phonetic: 'Je', color: letterColors[0] },
  { letter: 'K', example: 'Koala', emoji: '🐨', phonetic: 'Ka', color: letterColors[1] },
  { letter: 'L', example: 'Leu', emoji: '🦁', phonetic: 'Le', color: letterColors[2] },
  { letter: 'M', example: 'Morcov', emoji: '🥕', phonetic: 'Me', color: letterColors[3] },
  { letter: 'N', example: 'Nor', emoji: '☁️', phonetic: 'Ne', color: letterColors[4] },
  { letter: 'O', example: 'Ochi', emoji: '👁️', phonetic: 'O', color: letterColors[5] },
  { letter: 'P', example: 'Pește', emoji: '🐟', phonetic: 'Pe', color: letterColors[6] },
  { letter: 'Q', example: 'Qatar', emoji: '🌍', phonetic: 'Ku', color: letterColors[7] },
  { letter: 'R', example: 'Rață', emoji: '🦆', phonetic: 'Re', color: letterColors[8] },
  { letter: 'S', example: 'Soare', emoji: '☀️', phonetic: 'Se', color: letterColors[9] },
  { letter: 'Ș', example: 'Șarpe', emoji: '🐍', phonetic: 'Șe', color: letterColors[10] },
  { letter: 'T', example: 'Tigru', emoji: '🐯', phonetic: 'Te', color: letterColors[11] },
  { letter: 'Ț', example: 'Țânțar', emoji: '🦟', phonetic: 'Țe', color: letterColors[0] },
  { letter: 'U', example: 'Urs', emoji: '🐻', phonetic: 'U', color: letterColors[1] },
  { letter: 'V', example: 'Vulpe', emoji: '🦊', phonetic: 'Ve', color: letterColors[2] },
  { letter: 'W', example: 'Wombat', emoji: '🦘', phonetic: 'Dublu-ve', color: letterColors[3] },
  { letter: 'X', example: 'Xilofon', emoji: '🎵', phonetic: 'Ics', color: letterColors[4] },
  { letter: 'Y', example: 'Yoga', emoji: '🧘', phonetic: 'I-grec', color: letterColors[5] },
  { letter: 'Z', example: 'Zebră', emoji: '🦓', phonetic: 'Ze', color: letterColors[6] },
];

export const ENGLISH_ALPHABET: AlphabetLetter[] = [
  { letter: 'A', example: 'Apple', emoji: '🍎', phonetic: 'Ay', color: letterColors[0] },
  { letter: 'B', example: 'Balloon', emoji: '🎈', phonetic: 'Bee', color: letterColors[1] },
  { letter: 'C', example: 'Cat', emoji: '🐱', phonetic: 'See', color: letterColors[2] },
  { letter: 'D', example: 'Dog', emoji: '🐶', phonetic: 'Dee', color: letterColors[3] },
  { letter: 'E', example: 'Elephant', emoji: '🐘', phonetic: 'Ee', color: letterColors[4] },
  { letter: 'F', example: 'Flower', emoji: '🌸', phonetic: 'Ef', color: letterColors[5] },
  { letter: 'G', example: 'Giraffe', emoji: '🦒', phonetic: 'Gee', color: letterColors[6] },
  { letter: 'H', example: 'House', emoji: '🏠', phonetic: 'Aitch', color: letterColors[7] },
  { letter: 'I', example: 'Ice cream', emoji: '🍦', phonetic: 'Eye', color: letterColors[8] },
  { letter: 'J', example: 'Jellyfish', emoji: '🪼', phonetic: 'Jay', color: letterColors[9] },
  { letter: 'K', example: 'Koala', emoji: '🐨', phonetic: 'Kay', color: letterColors[10] },
  { letter: 'L', example: 'Lion', emoji: '🦁', phonetic: 'El', color: letterColors[11] },
  { letter: 'M', example: 'Moon', emoji: '🌙', phonetic: 'Em', color: letterColors[0] },
  { letter: 'N', example: 'Nest', emoji: '🪺', phonetic: 'En', color: letterColors[1] },
  { letter: 'O', example: 'Orange', emoji: '🍊', phonetic: 'Oh', color: letterColors[2] },
  { letter: 'P', example: 'Penguin', emoji: '🐧', phonetic: 'Pee', color: letterColors[3] },
  { letter: 'Q', example: 'Queen', emoji: '👑', phonetic: 'Cue', color: letterColors[4] },
  { letter: 'R', example: 'Rainbow', emoji: '🌈', phonetic: 'Ar', color: letterColors[5] },
  { letter: 'S', example: 'Sun', emoji: '☀️', phonetic: 'Ess', color: letterColors[6] },
  { letter: 'T', example: 'Tiger', emoji: '🐯', phonetic: 'Tee', color: letterColors[7] },
  { letter: 'U', example: 'Umbrella', emoji: '☂️', phonetic: 'You', color: letterColors[8] },
  { letter: 'V', example: 'Volcano', emoji: '🌋', phonetic: 'Vee', color: letterColors[9] },
  { letter: 'W', example: 'Whale', emoji: '🐋', phonetic: 'Double-you', color: letterColors[10] },
  { letter: 'X', example: 'Xylophone', emoji: '🎵', phonetic: 'Ex', color: letterColors[11] },
  { letter: 'Y', example: 'Yacht', emoji: '⛵', phonetic: 'Why', color: letterColors[0] },
  { letter: 'Z', example: 'Zebra', emoji: '🦓', phonetic: 'Zee', color: letterColors[1] },
];

export function getAlphabet(language: string): AlphabetLetter[] {
  return language === 'ro' ? ROMANIAN_ALPHABET : ENGLISH_ALPHABET;
}
