// Maps Romanian spoken text (lowercased) → pre-recorded MP3 asset.
// Keys match exactly what gets passed to speak() in the app.
export const RO_AUDIO: Record<string, number> = {
  // ── Phonetics ──────────────────────────────────────────────────────────────
  'a':         require('../../assets/audio/ro/phonetics/a.mp3'),
  'ă':         require('../../assets/audio/ro/phonetics/a_breve.mp3'),
  'â':         require('../../assets/audio/ro/phonetics/a_circ.mp3'),
  'be':        require('../../assets/audio/ro/phonetics/be.mp3'),
  'ce':        require('../../assets/audio/ro/phonetics/ce.mp3'),
  'de':        require('../../assets/audio/ro/phonetics/de.mp3'),
  'e':         require('../../assets/audio/ro/phonetics/e.mp3'),
  'fe':        require('../../assets/audio/ro/phonetics/fe.mp3'),
  'ghe':       require('../../assets/audio/ro/phonetics/ghe.mp3'),
  'ha':        require('../../assets/audio/ro/phonetics/ha.mp3'),
  'i':         require('../../assets/audio/ro/phonetics/i.mp3'),
  'î':         require('../../assets/audio/ro/phonetics/i_circ.mp3'),
  'je':        require('../../assets/audio/ro/phonetics/je.mp3'),
  'ka':        require('../../assets/audio/ro/phonetics/ka.mp3'),
  'le':        require('../../assets/audio/ro/phonetics/le.mp3'),
  'me':        require('../../assets/audio/ro/phonetics/me.mp3'),
  'ne':        require('../../assets/audio/ro/phonetics/ne.mp3'),
  'o':         require('../../assets/audio/ro/phonetics/o.mp3'),
  'pe':        require('../../assets/audio/ro/phonetics/pe.mp3'),
  'ku':        require('../../assets/audio/ro/phonetics/ku.mp3'),
  're':        require('../../assets/audio/ro/phonetics/re.mp3'),
  'se':        require('../../assets/audio/ro/phonetics/se.mp3'),
  'șe':        require('../../assets/audio/ro/phonetics/she.mp3'),
  'te':        require('../../assets/audio/ro/phonetics/te.mp3'),
  'țe':        require('../../assets/audio/ro/phonetics/tze.mp3'),
  'u':         require('../../assets/audio/ro/phonetics/u.mp3'),
  've':        require('../../assets/audio/ro/phonetics/ve.mp3'),
  'dublu-ve':  require('../../assets/audio/ro/phonetics/dublu_ve.mp3'),
  'ics':       require('../../assets/audio/ro/phonetics/ics.mp3'),
  'i-grec':    require('../../assets/audio/ro/phonetics/i_grec.mp3'),
  'ze':        require('../../assets/audio/ro/phonetics/ze.mp3'),

  // ── Alphabet example words ─────────────────────────────────────────────────
  'arici':     require('../../assets/audio/ro/words/arici.mp3'),
  'ăsta':      require('../../assets/audio/ro/words/asta.mp3'),
  'âncă':      require('../../assets/audio/ro/words/anca.mp3'),
  'balon':     require('../../assets/audio/ro/words/balon.mp3'),
  'casă':      require('../../assets/audio/ro/words/casa.mp3'),
  'dinozaur':  require('../../assets/audio/ro/words/dinozaur.mp3'),
  'elefant':   require('../../assets/audio/ro/words/elefant.mp3'),
  'floare':    require('../../assets/audio/ro/words/floare.mp3'),
  'găină':     require('../../assets/audio/ro/words/gaina.mp3'),
  'hartă':     require('../../assets/audio/ro/words/harta.mp3'),
  'iepure':    require('../../assets/audio/ro/words/iepure.mp3'),
  'înger':     require('../../assets/audio/ro/words/inger.mp3'),
  'jucărie':   require('../../assets/audio/ro/words/jucarie.mp3'),
  'koala':     require('../../assets/audio/ro/words/koala.mp3'),
  'leu':       require('../../assets/audio/ro/words/leu.mp3'),
  'morcov':    require('../../assets/audio/ro/words/morcov.mp3'),
  'nor':       require('../../assets/audio/ro/words/nor.mp3'),
  'ochi':      require('../../assets/audio/ro/words/ochi.mp3'),
  'pește':     require('../../assets/audio/ro/words/peste.mp3'),
  'qatar':     require('../../assets/audio/ro/words/qatar.mp3'),
  'rață':      require('../../assets/audio/ro/words/rata.mp3'),
  'soare':     require('../../assets/audio/ro/words/soare.mp3'),
  'șarpe':     require('../../assets/audio/ro/words/sarpe.mp3'),
  'tigru':     require('../../assets/audio/ro/words/tigru.mp3'),
  'țânțar':   require('../../assets/audio/ro/words/tantar.mp3'),
  'urs':       require('../../assets/audio/ro/words/urs.mp3'),
  'vulpe':     require('../../assets/audio/ro/words/vulpe.mp3'),
  'wombat':    require('../../assets/audio/ro/words/wombat.mp3'),
  'xilofon':   require('../../assets/audio/ro/words/xilofon.mp3'),
  'yoga':      require('../../assets/audio/ro/words/yoga.mp3'),
  'zebră':     require('../../assets/audio/ro/words/zebra.mp3'),

  // ── Game words (difficulty 1) ──────────────────────────────────────────────
  'mama':      require('../../assets/audio/ro/words/mama.mp3'),
  'tata':      require('../../assets/audio/ro/words/tata.mp3'),
  'apă':       require('../../assets/audio/ro/words/apa.mp3'),
  'sare':      require('../../assets/audio/ro/words/sare.mp3'),
  'pâine':     require('../../assets/audio/ro/words/paine.mp3'),
  'mere':      require('../../assets/audio/ro/words/mere.mp3'),
  'masă':      require('../../assets/audio/ro/words/masa.mp3'),
  'lună':      require('../../assets/audio/ro/words/luna.mp3'),
  'stea':      require('../../assets/audio/ro/words/stea.mp3'),

  // ── Game words (difficulty 2) ──────────────────────────────────────────────
  'pisică':    require('../../assets/audio/ro/words/pisica.mp3'),
  'câine':     require('../../assets/audio/ro/words/caine.mp3'),
  'pasăre':    require('../../assets/audio/ro/words/pasare.mp3'),
  'copac':     require('../../assets/audio/ro/words/copac.mp3'),
  'carte':     require('../../assets/audio/ro/words/carte.mp3'),
  'minge':     require('../../assets/audio/ro/words/minge.mp3'),
  'creion':    require('../../assets/audio/ro/words/creion.mp3'),

  // ── Game words (difficulty 3) ──────────────────────────────────────────────
  'bicicletă':   require('../../assets/audio/ro/words/bicicleta.mp3'),
  'calculator':  require('../../assets/audio/ro/words/calculator.mp3'),
  'televizor':   require('../../assets/audio/ro/words/televizor.mp3'),
  'fluture':     require('../../assets/audio/ro/words/fluture.mp3'),
  'girafă':      require('../../assets/audio/ro/words/girafa.mp3'),

  // ── New words (difficulty 1) ───────────────────────────────────────────────
  'nas':         require('../../assets/audio/ro/words/nas.mp3'),
  'mână':        require('../../assets/audio/ro/words/mana.mp3'),
  'pat':         require('../../assets/audio/ro/words/pat.mp3'),
  'tren':        require('../../assets/audio/ro/words/tren.mp3'),
  'mașină':      require('../../assets/audio/ro/words/masina.mp3'),
  'lapte':       require('../../assets/audio/ro/words/lapte.mp3'),
  'ou':          require('../../assets/audio/ro/words/ou.mp3'),
  'tort':        require('../../assets/audio/ro/words/tort.mp3'),
  'cal':         require('../../assets/audio/ro/words/cal.mp3'),
  'oaie':        require('../../assets/audio/ro/words/oaie.mp3'),
  'vacă':        require('../../assets/audio/ro/words/vaca.mp3'),
  'lup':         require('../../assets/audio/ro/words/lup.mp3'),

  // ── New words (difficulty 2) ───────────────────────────────────────────────
  'banană':      require('../../assets/audio/ro/words/banana.mp3'),
  'portocală':   require('../../assets/audio/ro/words/portocala.mp3'),
  'căpșună':     require('../../assets/audio/ro/words/capsuna.mp3'),
  'brânză':      require('../../assets/audio/ro/words/branza.mp3'),
  'roșie':       require('../../assets/audio/ro/words/rosie.mp3'),
  'ciupercă':    require('../../assets/audio/ro/words/ciuperca.mp3'),
  'broască':     require('../../assets/audio/ro/words/broasca.mp3'),
  'albină':      require('../../assets/audio/ro/words/albina.mp3'),
  'pinguin':     require('../../assets/audio/ro/words/pinguin.mp3'),
  'bufniță':     require('../../assets/audio/ro/words/bufnita.mp3'),
  'cerb':        require('../../assets/audio/ro/words/cerb.mp3'),
  'delfin':      require('../../assets/audio/ro/words/delfin.mp3'),
  'avion':       require('../../assets/audio/ro/words/avion.mp3'),
  'barcă':       require('../../assets/audio/ro/words/barca.mp3'),
  'autobuz':     require('../../assets/audio/ro/words/autobuz.mp3'),
  'cheie':       require('../../assets/audio/ro/words/cheie.mp3'),
  'oglindă':     require('../../assets/audio/ro/words/oglinda.mp3'),
  'telefon':     require('../../assets/audio/ro/words/telefon.mp3'),
  'curcubeu':    require('../../assets/audio/ro/words/curcubeu.mp3'),
  'frunză':      require('../../assets/audio/ro/words/frunza.mp3'),
  'zăpadă':      require('../../assets/audio/ro/words/zapada.mp3'),

  // ── New words (difficulty 3) ───────────────────────────────────────────────
  'ciocolată':   require('../../assets/audio/ro/words/ciocolata.mp3'),
  'înghețată':   require('../../assets/audio/ro/words/inghetata.mp3'),
  'crocodil':    require('../../assets/audio/ro/words/crocodil.mp3'),
  'hipopotam':   require('../../assets/audio/ro/words/hipopotam.mp3'),
  'papagal':     require('../../assets/audio/ro/words/papagal.mp3'),
  'veveriță':    require('../../assets/audio/ro/words/veverita.mp3'),
  'porumbel':    require('../../assets/audio/ro/words/porumbel.mp3'),
  'elicopter':   require('../../assets/audio/ro/words/elicopter.mp3'),
  'motocicletă': require('../../assets/audio/ro/words/motocicleta.mp3'),
  'ambulanță':   require('../../assets/audio/ro/words/ambulanta.mp3'),
  'umbrelă':     require('../../assets/audio/ro/words/umbrela.mp3'),
  'fotografie':  require('../../assets/audio/ro/words/fotografie.mp3'),
  'fereastră':   require('../../assets/audio/ro/words/fereastra.mp3'),
  'grădiniță':   require('../../assets/audio/ro/words/gradinita.mp3'),
  'bibliotecă':  require('../../assets/audio/ro/words/biblioteca.mp3'),
  'acvariu':     require('../../assets/audio/ro/words/acvariu.mp3'),
};
